config/routes.rb
Rails.application.routes.draw do
  root 'credit_cards#index'
  resources :credit_cards, only: [:index, :new, :create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
	include AASM

	STATUSES = [:pending, :approved, :disapproved]

	validates :email, :monthly_recurring_inflow, :monthly_recurring_outflow, presence: true
	validates :email, format: { with: URI::MailTo::EMAIL_REGEXP } 

	after_create :calculate_credibility_score
	before_create :find_credit_limit

	enum status: STATUSES

	aasm column: 'status' do
    state :pending, initial: true
    state :approved, :disapproved

    event :approve do
      transitions from: :pending, to: :approved
    end

    event :disapprove do
      transitions from: [:pending, :approved], to: :disapproved
    end
  end

  def calculate_credibility_score
  	credit_score = CredibilityScore.call(email)
  	if credit_score > 2
  		self.approve!
  	else
  		self.disapprove!
  	end
  end

  def find_credit_limit
  	maximum_possible_emi = (monthly_recurring_inflow/2 - monthly_recurring_outflow)
  	self.credit_limit = maximum_possible_emi * find_term_in_months(maximum_possible_emi)
  end

  private

  def find_term_in_months(emi)
  	term_in_months = (
  		if emi >= 0 && emi <= 5000
  		  6
  		elsif emi >= 5001 && emi <= 10000
  			12
  		elsif emi <= 10001 && emi >= 20000
  			18
  		elsif emi >= 20001
  			24
  		else 
  			0
  		end
  	)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/credit_cards_controller.rb
class CreditCardsController < ApplicationController

  # GET /credit_cards or /credit_cards.json
  def index
    @credit_cards = CreditCard.all
  end

  # GET /credit_cards/new
  def new
    @credit_card = CreditCard.new
  end

  # POST /credit_cards or /credit_cards.json
  def create
    @credit_card = CreditCard.new(credit_card_params)

    respond_to do |format|
      if @credit_card.save
        format.html { redirect_to credit_cards_path, notice: "Credit card is applied and sent to admin for approva;." }
        format.json { render :show, status: :created, location: @credit_card }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @credit_card.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Only allow a list of trusted parameters through.
    def credit_card_params
      params.require(:credit_card).permit(
        :email,
        :aadhar_number,
        :pan_number,
        :account_number,
        :ifsc,
        :monthly_recurring_inflow,
        :monthly_recurring_outflow
        )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def toastr_flash
	  flash.each_with_object([]) do |(type, message), flash_messages|
	    type = 'success' if type == 'notice'
	    type = 'error' if type == 'alert'
	    text = "<script>toastr.#{type}('#{message}', '', { closeButton: true, progressBar: true })</script>"
	    flash_messages << text.html_safe if message
	  end.join("\n").html_safe
	end
end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper
end

app/views/credit_cards/_form.html.erb
<%= form_for @credit_card do |f| %>
  <% if credit_card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(credit_card.errors.count, "error") %> prohibited this credit_card from being saved:</h2>

      <ul>
        <% credit_card.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, required: :true, class: "form-control" %>
  </fieldset>

  <fieldset class="form-group">
    <%= f.label :aadhar_number %>
    <%= f.text_field :aadhar_number, class: "form-control" %>
  </fieldset>

   <fieldset class="form-group">
    <%= f.label :pan_number %>
    <%= f.text_field :pan_number, class: "form-control" %>
  </fieldset>

   <fieldset class="form-group">
    <%= f.label :account_number, 'Bank Account Number' %>
    <%= f.text_field :account_number, class: "form-control" %>
  </fieldset>

  <fieldset class="form-group">
    <%= f.label :ifsc, 'Bank Account IFSC' %>
    <%= f.text_field :ifsc, class: "form-control" %>
  </fieldset>

  <fieldset class="form-group">
    <%= f.label :monthly_recurring_inflow %>
    <%= f.text_field :monthly_recurring_inflow, required: :true, class: "form-control" %>
  </fieldset>

  <fieldset class="form-group">
    <%= f.label :monthly_recurring_outflow %>
    <%= f.text_field :monthly_recurring_outflow, required: :true, class: "form-control" %>
  </fieldset>

  <div class="col-mx-12">
    <%= f.submit  "Apply", class: "btn btn-secondary rounded-pill mb-3 mr-2" %>
  </div>
<% end %>

app/views/credit_cards/index.html.erb
<div class="row mx-md-n5">
  <div class="col px-md-5">
    <div class="row">
      <div class="col-sm-offset-3">
        <h1>Credit Cards</h1>
        <%= link_to 'Apply credit card', new_credit_card_path %>
      </div>
    </div>

    <table class="table">
      <thead>
        <tr>
          <th>Email</th>
          <th>Credit Limit</th>
          <th>System Recommedation</th>
        </tr>
      </thead>

      <tbody>
        <% @credit_cards.each do |credit_card| %>
          <tr>
            <td><%= credit_card.email%></td>
            <td><%= credit_card.credit_limit %></td>
            <td><%= credit_card.status %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

app/views/credit_cards/new.html.erb
<div class="row mx-md-n5">
  <div class="col px-md-5">
    <h1>New Credit Card</h1>

    <%= render 'form', credit_card: @credit_card %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CreditCardApplication</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= toastr_flash %>
  </body>
</html>